#!/usr/bin/perl -w

# 生成 usys.S 汇编文件 - 系统调用存根(stubs)
# 此脚本为每个系统调用生成RISC-V汇编入口点
# 执行方式：./usys.pl > usys.S

# 输出文件头注释（避免手动编辑）
print "# generated by usys.pl - do not edit\n";

# 包含内核系统调用号定义头文件
print "#include \"kernel/syscall.h\"\n";

# 定义生成单个系统调用存根的子程序
sub entry {
    my $name = shift;  # 获取系统调用名称
    
    # 声明全局符号（使其他文件可调用）
    print ".global $name\n";
    
    # 定义标签（系统调用入口点）
    print "${name}:\n";
    
    # 将系统调用号加载到a7寄存器（SYS_${name}在syscall.h中定义）
    print " li a7, SYS_${name}\n";
    
    # 执行环境调用指令（陷入内核态）
    print " ecall\n";
    
    # 从子程序返回（返回到调用者）
    print " ret\n";
}

# 为每个系统调用生成存根
# ========================
entry("fork");    # 进程创建
entry("exit");    # 进程终止
entry("wait");    # 等待子进程
entry("pipe");    # 进程间通信
entry("read");    # 文件读取
entry("write");   # 文件写入
entry("close");   # 关闭文件描述符
entry("kill");    # 终止进程
entry("exec");    # 程序执行
entry("open");    # 打开文件
entry("mknod");   # 创建设备文件
entry("unlink");  # 删除文件
entry("fstat");   # 获取文件状态
entry("link");    # 创建硬链接
entry("mkdir");   # 创建目录
entry("chdir");   # 切换工作目录
entry("dup");     # 复制文件描述符
entry("getpid");  # 获取进程ID
entry("sbrk");    # 调整堆内存
entry("sleep");   # 进程休眠
entry("uptime");  # 获取系统运行时间